### ISSUE TITLE
今天出现了ai服务的问题

### ISSUE THREAD

**Issue by wdskwn** [volcengine/volc-sdk-nodejs#6]
使用1.12.0和1.13.0版本sdk都不可使用maas服务

使用官方给出的demo.js

问题：
node .\test.js
MaasError: Invalid request: invalid content-type=application/json; charset=utf-8
    at C:\Users\tao\Desktop\work\nodetest\node_modules\@volcengine\openapi\lib\services\maas\index.js:64:23
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///C:/Users/tao/Desktop/work/nodetest/test.js:38:1 {
  msg: 'Invalid request: invalid content-type=application/json; charset=utf-8',
  code: 'InvalidParameter',
  code_n: 1709808
}

**Comment by zenghongtu** [comment]
我也遇到了，啥时候能修复一下呢
